const page=document.body.dataset.page;
const definitions={
  motors:{file:'motors.json',title:'Motor data audit',description:'Electrical and holding-torque values loaded into the 24 V stepper-drive estimate.',source:'Ooznest Resources › System Control › Stepper Motors, then each motor product Specifications tab. Values were manually transcribed into motors.json.',fields:[['id','Data identifier'],['name','Customer-facing label'],['torque','Holding torque (kg-cm)'],['current','Rated phase current (A)'],['resistance','Phase resistance (Ω)'],['inductance','Phase inductance (mH)'],['voltage','Rated phase voltage (V)'],['steps','Full steps/rev']],caveat:'Holding torque is not running torque. The calculator derives running torque from these inputs using its conservative, unmeasured torque-speed model; measured torque-speed curves are not yet recorded for every motor.'},
  actuators:{file:'transmission.json',title:'Actuator / drive-system data audit',description:'Lead, efficiency, friction and travel data which convert motor torque into carriage force.',source:'Actuator product / assembly geometry and currently maintained calculator assumptions in transmission.json. Lead is geometric; efficiency and friction are model inputs until component-level test data is linked.',fields:[['id','Data identifier'],['name','Actuator product family'],['type','Drive type'],['lead','Travel per revolution (mm/rev)'],['efficiency','Mechanical efficiency'],['maxTravel','Modelled maximum travel (mm)'],['friction','Rolling / drive friction coefficient'],['note','Audit note']],caveat:'Efficiency, friction and maximum travel materially affect force and speed predictions. Treat them as review-required assumptions unless a linked tested source is added.'},
  gantries:{file:'gantryplates.json',title:'Gantry plate data audit',description:'Published plate-assembly ratings and recovered pre-factor ratings used by the calculator. Wheel-level fields have been removed because the published plate ratings already include the wheel calculation.',source:'Ooznest gantry-plate specification tabs. Every entry records its direct product URL and both the website-published figure and the figure recovered by multiplying the confirmed website factor of safety (3).',fields:[['id','Data identifier'],['name','Plate'],['mass','Plate mass (kg)'],['publishedSafetyFactor','Published FOS'],['published.radialStaticN','Published radial static (N)'],['actual.radialStaticN','Recovered radial static (N)'],['published.radialDynamicN','Published radial dynamic (N)'],['actual.radialDynamicN','Recovered radial dynamic (N)'],['published.axialStaticNByRailMm','Published axial static by rail width (N)'],['actual.axialStaticNByRailMm','Recovered axial static by rail width (N)'],['published.axialDynamicNByRailMm','Published axial dynamic by rail width (N)'],['actual.axialDynamicNByRailMm','Recovered axial dynamic by rail width (N)'],['published.mxStaticNmByRailMm','Published Mx by rail width (Nm)'],['actual.mxStaticNmByRailMm','Recovered Mx by rail width (Nm)'],['published.myStaticNm','Published My (Nm)'],['actual.myStaticNm','Recovered My (Nm)'],['published.mzStaticNm','Published Mz (Nm)'],['actual.mzStaticNm','Recovered Mz (Nm)'],['sourceUrl','Source page']],caveat:'The calculator will divide recovered actual ratings by the user-selected FOS. Plate direction selects radial or axial capacity. Axial values vary by rail width, so rail width must also be selected; no per-wheel multiplication is used.'}
};
const cfg=definitions[page];
const valueAt=(object,path)=>path.split('.').reduce((value,key)=>value?.[key],object);
const cell=(value,key)=>{if(value===undefined||value===null)return'—';if(key==='sourceUrl')return`<a href="${value}" target="_blank" rel="noreferrer">Source page</a>`;return typeof value==='object'?Object.entries(value).map(([width,rating])=>`${width} mm: ${rating}`).join('<br>'):String(value)};
async function render(){
 document.title=`Actuator Calculator — ${cfg.title}`;
 document.querySelector('h1').textContent=cfg.title; document.querySelector('#description').textContent=cfg.description; document.querySelector('#source').textContent=cfg.source; document.querySelector('#caveat').textContent=cfg.caveat;
 const rows=await fetch(`${cfg.file}?audit=1`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()});
 document.querySelector('#count').textContent=`${rows.length} records loaded live from ${cfg.file}`;
 document.querySelector('#headers').innerHTML=cfg.fields.map(([,label])=>`<th>${label}</th>`).join('');
 document.querySelector('#rows').innerHTML=rows.map(row=>`<tr>${cfg.fields.map(([key])=>`<td>${cell(valueAt(row,key),key)}</td>`).join('')}</tr>`).join('');
}
render().catch(error=>{document.querySelector('#count').textContent=`Could not load audit data: ${error.message}`;document.querySelector('#count').className='issue card'});
